### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by AggerTV** [APickledWalrus/skript-placeholders#13]
### Description

When I have skript-placeholders installed, skript breaks and sends multiple error messages in the console

### Steps to Reproduce

install skript-placeholder addon

### Expected Behavior

there should be no errors in console

### Errors / Screenshots

https://gist.github.com/AggerTV/4b2b016aba8245e7bd29a76cf6944f7d
(above is a paste of the latest.log)

### Server Information
* **Server version/platform:**       paper 1.12.2
* **skript-placeholders version:**                version 1.4
* **Skript version:**               2.5-beta2 (this also happened in earlier skript versions)
* **PlaceholderAPI version (if applicable):**                2.10.4

### Additional Context

I know for a fact, that this only occurs when I have the skript-placeholders addon installed

for reference, I first opened a ticket in the skript github site https://github.com/SkriptLang/Skript/issues/3327#issuecomment-677828843

**Comment by APickledWalrus** [comment]
This specific error doesn’t seem like it’s from my addon. What is in the autosmelt.sk script?

**Comment by AggerTV** [comment]
https://gist.github.com/AggerTV/060e73e05869f1d3c016968f91970a8b

**Comment by APickledWalrus** [comment]
Since this is unrelated to this addon, I'm going to close this issue.
If you are still having issues, I suggest you seek help in one of the Skript related discords or on Skript's official issue tracker.
