### ISSUE TITLE
Error when getting a value 

### ISSUE THREAD

**Issue by DavidVioMC** [APickledWalrus/skript-placeholders#15]
### Description
Getting an error when trying to get a value from SuperioSkyBlock2 placeholder.

### Steps to Reproduce
Code:
https://pastebin.com/USsJE1sY

### Expected Behavior
The variable should be the value of the placeholder

### Errors / Screenshots
https://pastebin.com/m7QCpd1X

### Server Information
* **Server version/platform:** Paper 1.12.2
* **skript-placeholders version:** 1.4
* **Skript version:** 2.5 beta 3
* **PlaceholderAPI version (if applicable):** 2.10.9
* **MVdWPlaceholderAPI version (if applicable):** N/A

**Comment by APickledWalrus** [comment]
Based on the error you sent, this problem is actually from SuperiorSkyblock, and you should report it to them. Thanks for the report though!
