### ISSUE TITLE
Works with 1.16.3?

### ISSUE THREAD

**Issue by Henriiig** [APickledWalrus/skript-placeholders#16]
1.5

### Description

Does this plugin work with 1.16.3, because when i use the plugin it will download the skript expansion which does not work and says this in the console: "WARN skript is attempting to register placeholders via a PlaceholderHook class which is no longer supported!"

It would be amazing if this could be fixed in any way.

**Comment by APickledWalrus** [comment]
What version of PlaceholderAPI are you running?

**Comment by Henriiig** [comment]
I am using 2.10.9, but is the plugin not downloading the papi skript expansion on load?

I also want to ask: does your Tuske fork with with 1.16.3? 

Btw I appreciate your work very much :) <3

**Comment by APickledWalrus** [comment]
The Skript PAPI expansion is not related to this plugin, and it was made by someone else. You can use this addon to create custom placeholders or use PAPI placeholders in your scripts.

As for skript-gui (the TuSKe GUI fork), it should work with 1.16. If you have any issues, please let me know on Discord or over on that repository.

**Comment by Henriiig** [comment]
Okay, thanks a lot. Do you know if TuSKE Gui works any better than skripts own gui system with "set {_gui} to a new chest inventory with 1 row..." and "On inventory click event"? :)

**Comment by APickledWalrus** [comment]
I personally prefer the TuSKe style, which is why I made the fork. I think it's easier to use overall, but you might get more control with vanilla.

Here's a link to the wiki if you want to check out how they work: https://github.com/APickledWalrus/skript-gui/wiki
