### ISSUE TITLE
<none> from console

### ISSUE THREAD

**Issue by arts7493** [APickledWalrus/skript-placeholders#17]
can't get value from console
it works from player
### Steps to Reproduce

command /testcommand:
	trigger:
		set {_test} to placeholder "~~" from sender
		message "%{_test}%"
### Server Information
* **Server version/platform:**  1.15.2 paper     
* **skript-placeholders version:**      1.4          
* **Skript version:**       2.4.1         
* **PlaceholderAPI version (if applicable):**    2.10.9            
* **MVdWPlaceholderAPI version (if applicable):**

**Comment by APickledWalrus** [comment]
It is not currently possible to get a placeholder from/using the console

**Comment by APickledWalrus** [comment]
I should expand on this:

If your placeholder doesn't need a player to work, you should just be able to leave it blank.

For example, with the placeholder `server_tps` from the Server expansion, you do not need to provide a player to get the value.
You could use the following code:
```
command /test:
	trigger:
		set {_p} to parse placeholder "server_tps"
		send "RESULT: '%{_p}%'" to player
```

This code will function properly :) If you have any issues with this, let me know.
