### ISSUE TITLE
Parsing from Offline Player

### ISSUE THREAD

**Issue by Dancull47** [APickledWalrus/skript-placeholders#21]
### Description

I'm attempting to get the result of a Placeholder for an Offline player. When I attempt to use this Skript `command /examine <offline player>:
    executable by: player
    trigger:
        set {_ping} to placeholder "vault_eco_balance_commas" from arg-1 # PlaceholderAPI
        send "Ping of %arg-1%: %{_ping}%" to player
` it sadly displays <none>. I've tried many different methods of getting this to work, but I haven't found a solution.

I can say, when I use `/papi parse MonzterYT %vault_eco_balance_commas%` it will return the result properly, even for offline players. Might there be anyway to get the result of a placeholder from an Offline player?

Skript-Placeholder: 1.5.1
Skript 2.5.2
PlaceholderAPI: 2.10.9

**Comment by APickledWalrus** [comment]
This should work.. I will take a look into this for you :)

**Comment by APickledWalrus** [comment]
I am not able to reproduce this issue running:

Skript 2.5.2
skript-placeholders 1.5.1
PlaceholderAPI 2.10.9

Here is a log of my actions:

![image](https://user-images.githubusercontent.com/29044720/107127002-47d2cf80-6881-11eb-9516-222d808ee1d2.png)

Here is the code I used:
```
command /test <offline player>:
	trigger:
		set {_p} to parse placeholder "vault_eco_balance_commas" as arg-1
		send "RESULT: '%{_p}%'" to executor
```

For this test, I was using Essentials to manage the economy (2.18.2.0)

**Comment by Dancull47** [comment]
Hey thanks for looking into this and providing another example. My issue was `set {_ping} to placeholder "vault_eco_balance_commas" from arg-1` rather than using `set {_p} to **parse placeholder** "vault_eco_balance_commas" **as** arg-1`.

This sorted it all out, appreciate it!

**Comment by APickledWalrus** [comment]
It should work with either syntax... maybe you have an addon that is conflicting with the other syntax. Happy to hear that it works :)
