### ISSUE TITLE
1 log handler was not stopped properly!

### ISSUE THREAD

**Issue by Mushkrem** [APickledWalrus/skript-placeholders#22]
**Hey! I get this error while running my skript and it's pretty much spamming the console, super annoying.**
_(at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:181))_

![image](https://user-images.githubusercontent.com/50112831/116948391-85c47180-ac7f-11eb-8df1-b2a9c4e89419.png)
![image](https://user-images.githubusercontent.com/50112831/116948681-5f530600-ac80-11eb-9578-e01585977fdf.png)

Additionally, while the error 'happens', as it doesn't for quite some time after the server's boot, placeholder I'm trying to register can't be retrieved by other plugins (RealScoreboard as in an example below). Here's my code, and the error's effect in-game:
![image](https://user-images.githubusercontent.com/50112831/116948724-8b6e8700-ac80-11eb-9053-9320aba5b4c3.png)
![image](https://user-images.githubusercontent.com/50112831/116948607-1dc25b00-ac80-11eb-8b00-c362e100d6b5.png)
btw. it flickers, the most of the time you're able to see your ping, but occasionally for around a second the only thing you can see is %player_ping%.

Installed skript addons (if needed):
- SkBee
- SkDragon
- SkJade
- SkQuery
- skRayFall
- **skript-placeholders**

**Comment by APickledWalrus** [comment]
Can you send the full error in something like pastebin? Also, how fast is your scoreboard refreshing?

**Comment by Mushkrem** [comment]
It's 10 ticks, also here's the full error; https://pastebin.com/raw/DWnyFeaM
See [02:06:49] that's where the error is somewhat a bit different.

**Comment by APickledWalrus** [comment]
I'm not entirely sure why this would be happening other than the super high refresh rate.. perhaps turn it up higher (maybe 60 ticks?) and let me know if you still have the issue

**Comment by Mushkrem** [comment]
Sorry for the late response, and honestly, I don't think it's caused by high refresh rate as I have 3 more placeholders made with your addon on it, and they aren't sending any errors. Yes, the problem still persists, but i figured out, that it happens only when i reload the skript a few times. Here's the whole code of that skript: https://pastebin.com/4tpewj2z maybe I missed some syntax?

**Comment by bilektugrul** [comment]
player's ping is already a integer/number. You don't have to parse it as an integer. 
Also, I'm not sure if this is just an example or production code but you can use Player PAPI expansion for getting ping.

**Comment by Mushkrem** [comment]
> player's ping is already a integer/number. You don't have to parse it as an integer.

Isn't it a string? Well, anyway without that line, the next if statement doesn't work.

![image](https://user-images.githubusercontent.com/50112831/116992104-d36bc900-acd5-11eb-8c48-e6f7f493a981.png)

As for that papi expansion to get ping, yeah I can do that, but i want ping be to colored depending on the player's current ping.

**Comment by APickledWalrus** [comment]
They mean that you should just do:

set {_var} to player's ping

**Comment by bilektugrul** [comment]
> > player's ping is already a integer/number. You don't have to parse it as an integer.
> 
> Isn't it a string? Well, anyway without that line, the next if statement doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/50112831/116992104-d36bc900-acd5-11eb-8c48-e6f7f493a981.png)
> 
> As for that papi expansion to get ping, yeah I can do that, but i want ping be to colored depending on the player's current ping.

Check PAPI config. There should be output replacement if i'm not wrong.

**Comment by Mushkrem** [comment]
Now it works without giving out errors even after reloading it, which is weird, but I guess it's fixed?
> Check PAPI config. There should be output replacement if I'm not wrong.

Not needed as pickledwalrus already gave a solution =)

Thanks for help and quick response!

**Comment by APickledWalrus** [comment]
It may have been the parsing expression that was adding some latency in getting the placeholder... happy to hear it works now though!
