### ISSUE TITLE
command works fine when run by the player but issues when run by console or for another player

### ISSUE THREAD

**Issue by DaMrZ** [APickledWalrus/skript-placeholders#23]
### Description

I run the command as the user and the command will run successfully but when I run the command as the console I receive an error: 
There is no player online whose name starts with 'universal DaMrZ'
/keycheck [< player >]
### Steps to Reproduce

run the command as user and it will take amount of tokens then give them the relevant crate key
run the command as console and receive the error
### Expected Behavior

Should be able to run the command through the console for another player and have them take away tokens and be provided the key
### Errors / Screenshots

There is no player online whose name starts with 'universal DaMrZ'
/keycheck [< player >]

### Server Information
* **Server version/platform:**  Tuinity b12d0cc      
* **skript-placeholders version:**  1.5              
* **Skript version:** 2.5.3               
* **PlaceholderAPI version (if applicable):**   2.10.9             
* **MVdWPlaceholderAPI version (if applicable):**                

### Additional Context

code: https://pastebin.com/fQUyphfq

**Comment by DaMrZ** [comment]
code: https://pastebin.com/fQUyphfq

**Comment by APickledWalrus** [comment]
This does not seem to be related to this addon. If you are trying to allow offline players to be used with your command, you can do `<offlineplayer>` instead of `<player>`
