### ISSUE TITLE
How do you activate it? Placeholders aren't understood.

### ISSUE THREAD

**Issue by plqsticflower** [APickledWalrus/skript-placeholders#25]
I just got the plugin and I'm not sure if I'm using it right because it isn't working for me.
I downloaded the ecould worldguard placeholders then put this placeholder into my skript, %worldguard_region_name%. But I get an error in my skript saying that it doesn't understand the expression. I tried other placeholders but none of them work in the skripts either, I know the placeholders are downloaded because they show up on my scoreboard. Am I missing a step or doing something wrong? I'm using version 1.5 of skript-placeholders.

**Comment by APickledWalrus** [comment]
There is an expression to get the value of a placeholder. You can see a tutorial here: https://github.com/APickledWalrus/skript-placeholders/wiki/Getting-the-Value-of-Placeholder(s)

**Comment by APickledWalrus** [comment]
Closed due to inactivity
