### ISSUE TITLE
EvtPlaceholderRequest NullPointerException

### ISSUE THREAD

**Issue by FinnChildress** [APickledWalrus/skript-placeholders#27]
### Description

Rarely when a player leaves my server it causes an error in Skript and the server enters a crashed state. 

### Steps to Reproduce

1. Install Skript
2. Install skript-placeholders
3. Have about 2000 players leave a server

### Expected Behavior

No errors

### Errors / Screenshots

https://gist.github.com/FinnChildress/95db2e3ade93fd4ca30927f4272a8554

### Server Information
* **Server version/platform:**       1.12.2 Paper
* **skript-placeholders version:**                1.5.1
* **Skript version:**                2.5.3
* **PlaceholderAPI version (if applicable):**                2.10.4
* **MVdWPlaceholderAPI version (if applicable):**          2.5.1      

### Additional Context

This has happened many times. I am only making an issue about it here so that it can stop.

**Comment by FinnChildress** [comment]
Not sure if it would be possible, but could you just remove the "return null" on line 50 of EvtPlaceholderRequest.java? I am not sure that you need the check to see if they are online at all, so you may be able to just do the cast without a check.

**Comment by APickledWalrus** [comment]
Hello! Thank you for this report. Please try the latest nightly build which you can download at https://github.com/APickledWalrus/skript-placeholders/suites/3240787961/artifacts/75215981

Let me know if this solves your issue and/or if you encounter any additional errors. If all is good, I will release a new version with this fix :)

**Comment by FinnChildress** [comment]
Great thank you! I will try that build and let you know if the issue happens again. Since it usually only happens about once a week or so, it may be multiple weeks until I know for sure that this issue has been fixed.

If I don't report anything in the next few days, please assume that it is fine and close the report. I will re-open this issue or make a new one if the bug happens again.

**Comment by APickledWalrus** [comment]
Marking this as complete as it has been a few weeks :)
