### ISSUE TITLE
Why this isn't working?

### ISSUE THREAD

**Issue by KSKgames** [APickledWalrus/skript-placeholders#28]
I made something super simple like example on the wiki:
on join:
	send "Your Ping: %placeholder ""player_ping"" from player%"

And skript says just like I wouldn't install this plugin (Can't understand this expression: placeholder ""player_ping"" from player . . .)
But I have everything I should, when I write /plugins, there is PlaceholderAPI, Skript, and of course your skript-placeholders.

Why isn't it working? How to fix it?

Skript version is 2.6-beta2    Your plugin version is v1.5.2-nightly-2cc7f3f.  I am on Paper-182 (MC. 1.17.1)

**Comment by APickledWalrus** [comment]
As of Skript 2.6, you no longer need to double up quotes in strings for expressions. It should just be 
`"%placeholder "player_ping" from player%"`

**Comment by KSKgames** [comment]
Thanks for quick reply and help, there also were some other problems which shown like the plugin wasn't just installed, but from what I see everything works for some reason, awesome plugin :) I searched so long, but found what needed, great!
