### ISSUE TITLE
seem not working on skript 2.6 with java 11+ (addon version: 1.5.2) 

### ISSUE THREAD

**Issue by denloself** [APickledWalrus/skript-placeholders#29]
the addon seem not working on skript 2.6 with java 11+

Error example:
`Can't understand this expression: placeholder ""tab_tabprefix"" from player`

skript-placeholder and skript verison:
 Skript 2.6
 skript-placeholder 1.5.2
Minecraft:
 git-Paper-714 (MC 1.16.5)

**Comment by APickledWalrus** [comment]
Could you send your code and placeholder plugin version? Thanks!

**Comment by denloself** [comment]
PlaceholderAPI version:
 2.10.9
Code:
`on chat:
    replace all "&h" with "<##3B3B3B>" in message
    set {level::%player%} to player's level
    set {dtag.%player%} to "&r &7~&r%placeholder ""deluxetags_tag"" from player%"
    if {dtag.%player%} contain "<none>":
        set {dtag.%player%} to ""
    if the player is op:
        if name of the player is "A1ph4_DenlosDX":
            set the chat format to "&8[&e%placeholder ""tab_tabprefix"" from player%&r%placeholder ""tab_customtabname"" from player%&7%{dtag.%player%}%&8] &7: &r%message%"
        if name of the player is "_Stresss_":
            set the chat format to "&8[&e%placeholder ""tab_tabprefix"" from player%&r%placeholder ""tab_customtabname"" from player%&7%{dtag.%player%}%&8] &7: &r%message%"
        if name of the player is "a1ph4_Yokossdx":
            set the chat format to "&8[&e%placeholder ""tab_tabprefix"" from player%&r%placeholder ""tab_customtabname"" from player%&7%{dtag.%player%}%&8] &7: &r%message%"
        if name of the player is "EpicSingleDog":
            set the chat format to "&8[&e%placeholder ""tab_tabprefix"" from player% &bEpicSingleDog&7~%placeholder ""deluxetags_tag"" from player%&8] &7: &r%message%"
        if name of the player is "ilvamoj":
            set {level::%player%} to player's level
            set the chat format to "&8[&7&l%placeholder ""tab_tabprefix"" from player%&r%placeholder ""tab_customtabname"" from player%%{dtag.%player%}%&8] &7: &r%message%"
    else:
        set {level::%player%} to player's level
        set the chat format to "&8[&7&l%placeholder ""tab_tabprefix"" from player%&r%placeholder ""tab_customtabname"" from player%%{dtag.%player%}%&8] &7: &r%message%"`

**Comment by APickledWalrus** [comment]
Ah, in Skript 2.6 you don't need to double the quotations in string expressions anymore. E.g. `"%placeholder "test" from player%"`

**Comment by denloself** [comment]
ok it works now, thanks a lot!
