### ISSUE TITLE
skript-placeholders and vault placeholders.

### ISSUE THREAD

**Issue by TheEstHennu** [APickledWalrus/skript-placeholders#30]
Hello! I have issue with getting value of vault placeholder.

Code:
 command /testagain:
    trigger:
        #set {vaultsuffix} to placeholder "vault_suffix"
        send "Your Ping: %placeholder "vault_suffix"% from player" to player
        #send the value of placeholder "Your seconds lived are %%vault_suffix%%. That is AWESOME!" from player to player

Error:
  [](https://pastebin.com/qiqrrEL3)https://pastebin.com/qiqrrEL3
  
Ingame error:
  
![image_2021-12-05_134158](https://user-images.githubusercontent.com/77569703/144744976-f2c45db8-fffd-48dc-97ed-512734031da6.png)

**Comment by APickledWalrus** [comment]
Make sure thé `from player` part is within the expression. E.g. `send "Your Ping: %placeholder "vault_suffix" from player%" to player`
However, it should not throw an internal error like this if an error occurs. This can be improved.

**Comment by TheEstHennu** [comment]
Maybe it's because of any my addons?
I have installed skungee, ersatz, skript-placeholders, vixio, skquery and skbee.

**Comment by APickledWalrus** [comment]
Sorry... I never replied to this :(

This addon is a replacement for Ersatz, so you should not use it.

**Comment by APickledWalrus** [comment]
I'm going to close this issue since it's been so long, but please feel free to open a new one if you are still having problems 🙂
