### ISSUE TITLE
NoSuchElementException PlaceholderAPIListener.java:47

### ISSUE THREAD

**Issue by FinnChildress** [APickledWalrus/skript-placeholders#33]
### Description
Rarely when checking a custom placeholder for a player as they leave the server it causes an error in Skript and the server enters a crashed state.
Seems to have something to do with **PlaceholderAPIListener.java:47**

### Steps to Reproduce
1. Create a custom placeholder via skript-placeholders
2. Add something to check the placeholder when the player leaves the server
3. Have about 5,000 players leave the server

### Expected Behavior
No errors

### Errors / Screenshots
https://gist.github.com/FinnChildress/c42a10a6f1b1874a70acf9e833c27a7a

### Server Information
* **Server version/platform:**       1.12.2 Paper
* **skript-placeholders version:**                1.5.2
* **Skript version:**                2.5.3
* **PlaceholderAPI version (if applicable):**                2.10.9
* **MVdWPlaceholderAPI version (if applicable):**          3.1.1    

### Additional Context
This has been happening for a while now, but it is so infrequent that I have not felt much pressure to make a report.

**Comment by APickledWalrus** [comment]
I'm going to close this issue since it's been so long, but please feel free to open a new one if you are still having problems 🙂
