### ISSUE TITLE
Relational Placeholders

### ISSUE THREAD

**Issue by ShaneBeee** [APickledWalrus/skript-placeholders#34]
### Description
Someone on discord was talking about this, so I figured I'd suggest it.
If you could please add "Relational Placeholders" that would be great

https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#relational-placeholders

**Comment by APickledWalrus** [comment]
Sure, I'll look into adding support for creating & obtaining them :)

**Comment by APickledWalrus** [comment]
Almost two years later, this will be coming in 1.7.0 lol

**Comment by APickledWalrus** [comment]
It's finally here! Thanks for the suggestion.
