### ISSUE TITLE
Held item

### ISSUE THREAD

**Issue by masterwebb** [APickledWalrus/skript-placeholders#36]
How to i set a players current held item to a slot?

on rightclick:
	if player's tool is netherite chestplate:
		set {armor::%player%::chest} to player's held item
#code 
			make gui slot 5 with {stats::%player%::rod} named "Your Stats:":
			open last gui to player

**Comment by zxcbelaz** [comment]
### 

- [ ] @ #1. > [`_****_`](url)

**Comment by APickledWalrus** [comment]
IIRC you can just do `set player's tool to ...` or even `set player's held item to ...`

I recommend checking out a community like skUnity for support like this, as it's not quite specific to this addon.
