### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by czychuuu** [APickledWalrus/skript-placeholders#38]
### Description
idk bug report

### Steps to Reproduce
on placeholderapi placeholder request for the prefix "skript":

### Expected Behavior
skript load normally

### Errors / Screenshots
https://pastebin.com/nBzRuP1r

### Server Information
Server version/platform: paper 1.19.3
skript-placeholders version: 1.5.2
Skript version: 2.6.4
PlaceholderAPI version (if applicable): 2.11.3
MVdWPlaceholderAPI version (if applicable):

**Comment by APickledWalrus** [comment]
Doesn't seem to be related to this addon. What other addons do you have installed?

**Comment by czychuuu** [comment]
> Doesn't seem to be related to this addon. What other addons do you have installed?

i think it is
Current node: on placeholderapi placeholder request for the prefix "skript": (core.sk, line 1)
[16:53:34 ERROR]: #!#! Current item: null

**Comment by APickledWalrus** [comment]
Looking at the error it seems to be an issue with SkQuery
