### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by xHez** [APickledWalrus/skript-placeholders#39]
### Description

i'm using selfmade placeholder using skript-placeholders and it doesnt clear lagg and keeps on using up 20gb of ram on 10 players.
### Steps to Reproduce

on placeholderapi placeholder request for the prefix "player":
    if the identifier is "hearts":
        if the player is online:
            set the result to "%{hearts::%player's uuid%}%"
### Server Information
* **Server version/platform:**       
* **skript-placeholders version:**                
* **Skript version:**                
* **PlaceholderAPI version (if applicable):**                
* **MVdWPlaceholderAPI version (if applicable):**

**Comment by APickledWalrus** [comment]
You might run into issues if your placeholder is being requested too often. Are you still having issues? Apologies for not getting back to you on this.

**Comment by APickledWalrus** [comment]
Closing in favor of #50
