### ISSUE TITLE
wont get value from the placeholder

### ISSUE THREAD

**Issue by arial-improved** [APickledWalrus/skript-placeholders#42]
version 1.5.2

i have a skript that is a randomised shop and need to use a custom plugin for the economy, it has a placeholder to show value but when i try to get the value in the skript to see if the player has enough to buy an item it always says they dont even if they do.

here is the code: https://pastebin.com/qbQPFxBs

**Comment by arial-improved** [comment]
can someone help please, i need to release this as soon as i can

**Comment by APickledWalrus** [comment]
Sorry I did not get back to you on this. All placeholder values are text. You would need to parse the value of the placeholder as a number first.
