### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by lazycaps** [APickledWalrus/skript-placeholders#44]
### Version
1.5.2
### Description
I'm making a skript, and I have a gamemode called "fastbuilder".
There is a placeholder called %fastbuilder_time%

here is my skript

on stepping on a pressure plate:
    if event-player is player:
        send "&f&m--------------------------" to player
        send "&f     &eYou had a time of:" to player
        send "       Your Ping: %placeholder ""fastbuilder_time"" from fastbuilder%" # PlaceholderAPI Example
        send "&f&m--------------------------" to player

**Comment by lazycaps** [comment]
![image](https://github.com/APickledWalrus/skript-placeholders/assets/135090883/15ef00e0-a3c7-4eae-a9c7-b0b3bc99701e)

**Comment by APickledWalrus** [comment]
Refer to https://github.com/APickledWalrus/skript-placeholders/wiki/Getting-the-Value-of-Placeholder(s)
