### ISSUE TITLE
Placeholder from the plugin "Statistics" not working

### ISSUE THREAD

**Issue by dabbadboiboss** [APickledWalrus/skript-placeholders#46]
Version 1.5.2
### Description

Hello all,
I've been trying to connect skript and PAPI for a while now, and it just doesn't work.
I've downloaded the plugin using /papi ecloud download, I've reloaded papi, I've downloaded skript-placeholders, but nothing works and skript doesn't recognize the placeholders
If anyone could help, **please** reply ASAP, as I need to get this finished soon

Pictures:
![image](https://github.com/APickledWalrus/skript-placeholders/assets/51846337/a1b193e6-6678-4779-a159-85d0cc7a5f5b)
![image](https://github.com/APickledWalrus/skript-placeholders/assets/51846337/fef45824-0ffb-4ea5-946e-6277c04331b2)
![image](https://github.com/APickledWalrus/skript-placeholders/assets/51846337/4328f622-b14b-4860-80ea-3693848a7360)

Thank you!

**Comment by APickledWalrus** [comment]
Sorry for the delay. You'll have to use the placeholder expression: https://github.com/APickledWalrus/skript-placeholders/wiki/Getting-the-Value-of-Placeholder(s)

**Comment by APickledWalrus** [comment]
I'm going to go ahead and close this issue, but please feel free to open a new one if you continue to experience issues.
