### ISSUE TITLE
Problem on sk-2.7.x

### ISSUE THREAD

**Issue by ZConnorZ** [APickledWalrus/skript-placeholders#48]
### Description
On version 2.7, third-party plugins display placeholders created in sk with a delay. For example, DecentHolo took 1 second to display 10 lines. I also checked with the TAB plugin, too.

### Steps to Reproduce
1. Create your placeholder on SK.
2. Insert it into any plugin that can display placeholders. (For example, I inserted several lines into DecentHolograms to display my placeholder)
3. Most likely the plugin will need 100ms+ to display these placeholders.

### Errors / Screenshots
![image](https://github.com/APickledWalrus/skript-placeholders/assets/45974097/8af21bbc-0784-4a04-8129-5f3f0116463f)

### Server Information
* **Server version/platform:**       1.20.1 purpur
* **skript-placeholders version:**                v1.5.2
* **Skript version:**                2.7.1
* **PlaceholderAPI version (if applicable):**                2.11.4

**Comment by APickledWalrus** [comment]
Sorry I didn't get back to you on this. I'm tracking these reports at #50.
