### ISSUE TITLE
No api version.

### ISSUE THREAD

**Issue by ninjaguardian** [APickledWalrus/skript-placeholders#51]
### Description

My console shows `Legacy plugin skript-placeholders v1.5.2 does not specify an api-version.`
### Steps to Reproduce

Download the plugin?
### Expected Behavior

Not to give this error.
### Server Information
* **Server version/platform:**       This server is running Paper version git-Paper-"f042be6"
* **skript-placeholders version:**                 1.5.2
* **Skript version:**                  2.7.2
* **PlaceholderAPI version (if applicable):**                 2.11.5
* **MVdWPlaceholderAPI version (if applicable):**

**Comment by APickledWalrus** [comment]
I'll work on this for the next version :)
