### ISSUE TITLE
variables inside placeholders 

### ISSUE THREAD

**Issue by czychuuu** [APickledWalrus/skript-placeholders#53]
### Description

title
example:
on placeholderapi placeholder request for the prefix "custom":
  if the identifier is "aassdd_{_variable}"
    if {_variable} is "something"
      set the result to " "
    set the result to function({_variable})

**Comment by APickledWalrus** [comment]
would it set the variable based on the identifier? im not too sure what you're requesting.

**Comment by czychuuu** [comment]
to be able to make placeholder like some plugins do eg name_<number> and it outputs formatted time for example name_3 outputs "3s" name_1000 outputs "16m 40s" etc

**Comment by APickledWalrus** [comment]
I'd probably recommend parsing this yourself with existing Skript syntax - it shouldn't be too difficult :)

**Comment by czychuuu** [comment]
this is just a example what i mean

**Comment by APickledWalrus** [comment]
Unfortunately, I do not think this is feasible to implement and am going to stick with the recommendation of parsing this yourself (Skript has the `parsed as` expression which would simplify this).
