### ISSUE TITLE
Change the placeholder value.

### ISSUE THREAD

**Issue by Alfrediscool12** [APickledWalrus/skript-placeholders#55]
So i have a pretty specific problem. I use skript to make a custom level varible "{level::%player's uuid%}". And i wan't that varible to be on a leaderboard (i use ajleaderboard). And ajleadboards only allow placeholders. 

So i though i could do something like this with this plugin:
every 1 seconds:
	loop all players:
		set placeholder "statistic_fish_caught" to {level::%loop-player's uuid%}
		
		
		
But you can't set a placeholder to any value. I would love this as a feature!

**Comment by APickledWalrus** [comment]
You can create placeholders using this addon. You can review the Wiki entry on how to do so here: https://github.com/APickledWalrus/skript-placeholders/wiki/Registering-Placeholders
