### ISSUE TITLE
Placeholder Behavior: In-game vs Console

### ISSUE THREAD

**Issue by Bilal380ishere** [APickledWalrus/skript-placeholders#56]
**Description:**
Using placeholders in a script works well when a player runs a command in-game; the placeholders function properly. However, when the same command is run from the console, it outputs 'none' for the placeholder.

**Steps to Reproduce**
1. Run a command using placeholders in-game.
2. Run the same command from the console.
3. Observe the output.

**Expected Behavior**
The placeholder should function properly both when executed by a player in-game and from the console, providing the expected output.

**Server Information**
Server version/platform: 1.20.4 Paper
Skript version:** Latest
skript-placeholders version: 1.6.0

**Skript Example:**

```
command /test <text>:
    executable by: console, players
    trigger:
        broadcast "%placeholder "worldguard_region_name" from arg-1% %arg-1%"
```

**Comment by APickledWalrus** [comment]
I am going to go ahead and close this issue, but please feel free to reply again if the above does not resolve your issue.
