### ISSUE TITLE
Breaking placeholders (luckperms?)

### ISSUE THREAD

**Issue by MennoGamed** [APickledWalrus/skript-placeholders#57]
# Description
Hi there,
It seems that since the 1.6.0 update something is not going quite right. Placeholders I use for Luckperms' prefix, "%luckperms_prefix%", don't seem to do anything anymore. I don't use any other placeholders, so I can't confirm the rest.

![afbeelding](https://github.com/APickledWalrus/skript-placeholders/assets/64696706/2dc9a420-7f25-437c-a99a-50e11764ea48)
![afbeelding](https://github.com/APickledWalrus/skript-placeholders/assets/64696706/24c91fc9-c384-43d3-8308-252e63a64c61)

# Steps to Reproduce
Create a paper server, and download the plugins below:
- LuckPerms-Bukkit-5.4.121
- PlaceholderAPI-2.11.5
- Skript-2.8.4
- skript-placeholders-1.6.0

- Download the "Luckperms" extension via PAPI's ecloud.
- Set a prefix for luckperms' "Default" rank. This must have color codes like &2!

You can use the added script to test it. You will see in chat that the player's prefix will not appear in chat.
Simple Chat Skript: [chat.txt](https://github.com/APickledWalrus/skript-placeholders/files/14952108/chat.txt)
# Expected Behavior
The players' prefix should simply appear in chat due to the Luckperms prefix. This should work using the "`%placeholder "luckperms_prefix" from player%`".

# Errors
Unfortunately, the plugin does not give any errors. It simply doesn't work with the prefixes of Luckperms.

# Server Information
* **Server version/platform:** _Paper 1.20.4, build 478_
* **skript-placeholders version:** _v1.6.0_
* **Skript version:** _v2.8.4_
* **PlaceholderAPI version:** _v2.11.5_

**Comment by APickledWalrus** [comment]
Is it that the prefix or not working or just the color/formatting? Try `colored placeholder "luckperms_prefix" from player`

**Comment by MennoGamed** [comment]
It was the color/formatting that didn't work.
The option you gave me was indeed the solution, thx! Since when is that a thing?

With `colored placeholder "luckperms_prefix" from player` it indeed works without any problems.

**Comment by APickledWalrus** [comment]
I apologize for not getting back to you. There were some changes made, and as a result, coloring is no longer added by default. Let me know if that solution stops working for you though.

**Comment by MennoGamed** [comment]
Hi,
So far it has solved everything, and I have had a problem free experience! 😊
