### ISSUE TITLE
Does not work anymore?

### ISSUE THREAD

**Issue by bloggy** [APickledWalrus/skript-placeholders#7]
- This server is running Paper version git-Paper-617 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Loading PlaceholderAPI v2.10.4
- Loading skript-placeholders v1.3.1
- Enabling Skript v2.3.6

Test script:

```
command /testy:
	trigger:
		set {_ping} to placeholder "player_biome"
		broadcast "your ping is %{_ping}%"
```

result is `<none>`

**Comment by APickledWalrus** [comment]
Are you sure the player expansion is successfully loaded? Do any other placeholders work?

**Comment by bloggy** [comment]
I have also tested it with "server_tps", same result: none

I tried this as well:
```
on placeholder request with prefix "custom":
	if the identifier is "hey": 
		# %custom_hey%
		set the result to "hi there %player%!"
```
This throws an error:
https://i.imgur.com/wJKc9Bm.png

**Comment by bloggy** [comment]
Update: you were right: the expansions were not correctly loaded! Thanks a lot!
But this issue still exists (or how can I create my own placeholder?):

on placeholder request with prefix "custom":
	if the identifier is "hey": 
		# %custom_hey%
		set the result to "hi there %player%!"
```
This throws an error:
https://i.imgur.com/wJKc9Bm.png

**Comment by APickledWalrus** [comment]
Do you have the skript expansion installed? Try using this but with a different name, such as bloggy_test.

**Comment by bloggy** [comment]
You are right - that fixed the issue - thanks a lot and keep up the good work :-) !!!

**Comment by APickledWalrus** [comment]
I’ll update the doc examples so that they are correct.
