### ISSUE TITLE
[Suggestion] Allowing the result of a placeholder request to return more than a string

### ISSUE THREAD

**Issue by shivasuc** [APickledWalrus/skript-placeholders#8]
The result of placeholder requests should be able to be set to more types like numbers. Plugins like leaderheads accept numeric placeholders to create leaderboards. Other plugins already return numeric values so i would like it if this addon could too.

**Comment by APickledWalrus** [comment]
Unfortunately, you can only return string values through PlaceholderAPI (see https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderHook.java)

I’m not sure how plugins like LeaderHeads handle it, but it should be able to accept an input such as "10" and convert it.
